# Generated by Django 5.2.13 on 2026-05-04 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_coursereview_enrollment"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="course",
            new_name="courses_cou_instruc_9a1002_idx",
            old_name="courses_cou_instruc_idx",
        ),
        migrations.RenameIndex(
            model_name="lesson",
            new_name="courses_les_course__dc0bc6_idx",
            old_name="courses_les_course_idx",
        ),
    ]
